FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y python3 &&\
    apt-get install -y openssh-server
RUN mkdir -p /home/.ssh
WORKDIR /home
COPY app.py /home/app.py
COPY machine3.pub /home/.ssh/machine3.pub
CMD ["/usr/bin/python3","./app.py"]
